USE customer_shopping_behaviour;

SELECT * 
FROM customer_shopping_behaviour.customer;

/*Q1. What is the total revenue generated by male vs. female customers?*/

SELECT 
    Gender, SUM(PurchaseAmountUSD) AS Revenue
FROM
    customer_shopping_behaviour.customer
GROUP BY Gender;

/*Q2. Which customers used a discount but still spent more than the average purchase amount? */

SELECT 
    CustomerID, PurchaseAmountUSD
FROM
    customer
WHERE
    DiscountApplied = 'Yes'
        AND PurchaseAmountUSD >= (SELECT 
            AVG(PurchaseAmountUSD)
        FROM
            customer);

/*Q3. Which are the top 5 products with the highest average review rating?*/

SELECT 
    ItemPurchased,
    AVG(ReviewRating) AS AvgRating
FROM 
    customer
GROUP BY 
    ItemPurchased
ORDER BY 
    AvgRating DESC
LIMIT 5;

/*Q4. Compare the average Purchase Amounts between Standard and Express Shipping.*/

SELECT 
    ShippingType,
    AVG(PurchaseAmountUSD) AS AvgPurchaseAmount
FROM 
    customer
WHERE 
    ShippingType IN ('Standard', 'Express')
GROUP BY 
    ShippingType;
    
/*Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.*/

SELECT SubscriptionStatus,
       COUNT(CustomerID) AS total_customers,
       ROUND(AVG(PurchaseAmountUSD),2) AS avg_spend,
       ROUND(SUM(PurchaseAmountUSD),2) AS total_revenue
FROM customer
GROUP BY SubscriptionStatus
ORDER BY total_revenue,avg_spend DESC;

/*Q6. Which 5 products have the highest percentage of purchases with discounts applied?*/

SELECT ItemPurchased,
       ROUND(100.0 * SUM(CASE WHEN DiscountApplied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY ItemPurchased
ORDER BY discount_rate DESC
LIMIT 5;

/*Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.*/

SELECT 
    CASE
        WHEN PreviousPurchases = 0 THEN 'New'
        WHEN PreviousPurchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS CustomerSegment,
    COUNT(*) AS SegmentCount
FROM 
    customer
GROUP BY 
    CustomerSegment;
    
/*Q8. What are the top 3 most purchased products within each category? */

SELECT 
    Category,
    ItemPurchased,
    PurchaseCount
FROM (
    SELECT 
        Category,
        ItemPurchased,
        COUNT(*) AS PurchaseCount,
        ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(*) DESC) AS rn
    FROM 
        customer
    GROUP BY 
        Category, ItemPurchased
) ranked
WHERE rn <= 3
ORDER BY Category, PurchaseCount DESC;

/*Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?*/

SELECT SubscriptionStatus,
       COUNT(CustomerID) AS repeat_buyers
FROM customer
WHERE PreviousPurchases > 5
GROUP BY SubscriptionStatus;

/*Q10. What is the revenue contribution of each age group? */

SELECT 
  CASE 
    WHEN age BETWEEN 18 AND 25 THEN 'Young Adult'
    WHEN age BETWEEN 26 AND 40 THEN 'Middle Aged'
    WHEN age BETWEEN 41 AND 60 THEN 'Adult'
    ELSE 'Senior'
  END AS AgeGroup,
  SUM(PurchaseAmountUSD) AS TotalRevenue
FROM customer
GROUP BY AgeGroup;



    
   



